version: '2'

services:

   db:
     container_name: mysql-latest
     image: mysql:latest
     volumes:
       - "./db_data:/var/lib/mysql"
     ports:
       - "8306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
       - db
    environment:
      PMA_ARBITRARY: 1
    ports:
     - 8080:80
    volumes:
     - /sessions
    external_links:
     - db_server:db

   wordpress:
     container_name: wpchrono-wordpress
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes: 
       - "../wp-chrono:/var/www/html/wp-content/plugins/wp-chrono"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data:
    wp-chrono: